#!/usr/bin/env python3
"""Embed the retail UDTA/UGRD payloads into the core as C++ arrays.

    python3 scripts/gen-default-data.py

A map that carries no UDTA section still has unit footprints, movement domains
and flags — the game falls back to its own table. Without that table the editor
thinks every unit is 1x1 and knows nothing about what may be placed where, so
the defaults have to travel with the core rather than with a game install.

Regenerate after changing data/*.bin; the output is checked in.
"""

from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "src/PUDForgeCore/default_data.cpp"

SOURCES = [
    ("kDefaultUdta", "data/default-udta.bin", 5696),
    ("kDefaultUgrd", "data/default-ugrd.bin", 782),
]

lines = [
    "// Retail UDTA/UGRD payloads, embedded so a map without those sections",
    "// still has correct footprints, flags and upgrade data.",
    "//",
    "// GENERATED by scripts/gen-default-data.py from data/*.bin. Do not edit.",
    "",
    '#include "constants.hpp"',
    "",
    "namespace pf {",
    "",
]

for name, rel, expect in SOURCES:
    raw = (ROOT / rel).read_bytes()
    if len(raw) != expect:
        raise SystemExit(f"{rel}: expected {expect} bytes, found {len(raw)}")
    lines.append(f"const uint8_t {name}[{len(raw)}] = {{")
    for i in range(0, len(raw), 16):
        chunk = ", ".join(f"0x{b:02x}" for b in raw[i:i + 16])
        lines.append(f"    {chunk},")
    lines.append("};")
    lines.append(f"const int {name}Size = {len(raw)};")
    lines.append("")

lines.append("}  // namespace pf")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")
